io_root_directory: <%= OBJECT_ORIENTED_BEAGLEBONE_BLACK_ROOT %>/tmp/sys/class
slots_directory: <%= OBJECT_ORIENTED_BEAGLEBONE_BLACK_ROOT %>/tmp/sys/devices/bone_capemgr.9
device_directory: <%= OBJECT_ORIENTED_BEAGLEBONE_BLACK_ROOT %>/tmp/sys/devices/ocp.3